#!/bin/bash

#Search The Student ID
function searchID(){
	#ID Format 2 Digits |WMR|5 Digits hence ^\d{2}(WMR)\d{5}$ "
	echo -n "Enter Student ID: "; read id
	
	#Auto Capitilise The 3 Letters When Necessary
	id=${id^^} 
	regexID=^[0-9]{2}WMR[0-9]{5}$
	
	#check if input empty
	if [ -z "$id" ] 
	then
		#Empty ID
		emptyWrongID=1
		./formHeaderFormat "Search Student Details Form"
		echo  "Enter Student ID: "$id
		echo "Student ID Is Empty. Please Enter Again in 2 Seconds."
		sleep 2
		
	#Check if Student ID Is Found
	elif grep -qF "$id" student.txt
	then
		emptyWrongID=0
		found=1
		student=$(grep $id student.txt | cut -b 16-)
		
		defaultIFS=$IFS
		IFS=":" ## internal field separator 
		read -ra infoArr <<< "$student" ## redirect student info into array
		IFS=$defaultIFS
		
		clear
		./formHeaderFormat "Search Student Details Form"
		echo  "Enter Student ID: "$id
		
		echo -e "\n\nStudent Name    : ""${infoArr[0]}"
		echo -e "\n\nContact Number  : ""${infoArr[2]}"
		echo -e "\n\nMailing Address : ""${infoArr[3]}"
		echo -e "\n\nEmail           : ""${infoArr[4]}"
	
	#Check if Student ID Format is Correct
	elif ! [[ $id =~ $regexID ]]
	then
		#Wrong ID Format
		emptyWrongID=1
		echo "Incorrect Student ID Format. Please Enter Again in 3 Seconds (Format: 11WMR11111)"
		sleep 3
		clear	
	
	else
		#Correct Format ID But Not Found
		emptyWrongID=0
		found=0
		clear
		./formHeaderFormat "Search Student Details Form"
		echo  "Enter Student ID: "$id
		echo -e "\nStudent ID Not Found"
	fi
}

#Search for another student
function searchAnotherStudent(){
	echo -ne "\n\nSearch Another Student? (y)es or (q)uit: "; read choice 
	choice=${choice,,}
	echo 
	case "$choice" in
		y)
			#Do Nothing
			:
			;;
		q) 
			read -n1 -s -r -p $"Press(q) to return to College Management Menu"  key
			searchNextStudent=0

			#Return only when "q" is pressed
			while [ "$key" != "q" ] 
			do
				read -n1 -s -r -p "" key
				if [ "$key" = "q" ]; then
					break
				fi
			done
			;;
		*)
			echo "Invalid Choice. Please Enter Again in 2 Second."
			sleep 2
			clear
			./formHeaderFormat "Search Student Details Form"
			if [ $emptyWrongID -eq 0 -a $found -eq 1 ]
			then
				echo  "Enter Student ID: "$id
				echo -e "\n\nStudent Name    : ""${infoArr[0]}"
				echo -e "\n\nContact Number  : ""${infoArr[2]}"
				echo -e "\n\nMailing Address : ""${infoArr[3]}"
				echo -e "\n\nEmail           : ""${infoArr[4]}"
			else
				echo  "Enter Student ID: "$id
				echo -e "\nStudent ID Not Found"
			fi
			searchAnotherStudent
			;;
	esac
}

#Program Starts Here
searchNextStudent=1
#Check Empty or Wrong Format Flag
emptyWrongID=0
while [ $searchNextStudent -eq 1 ]
do
	./formHeaderFormat "Search Student Details Form"
	searchID
	
	if [ $emptyWrongID -eq 1 ]
	#if Empty or Wrong Student ID Format
	then
		continue
	else
		#When Found
		searchAnotherStudent
	fi
	
	if [ $searchNextStudent -eq 0 ]
	then
		clear
		#Go back to main menu
		exit
	else
		#find another student
		continue
	fi
done
